### ISSUE TITLE
Attachments as byte.buffer

### ISSUE THREAD

**Issue by aphsa** [harranali/mailing#3]
Can you add a option to add attachments as memory instead of files.

**Comment by harranali** [comment]
Hi @aphsa,
first I would like to thank you for your suggestion,
it's not a common thing that developers do everyday, to have files in the memory, so there is no need to implement the handling of attaching the in memory files, instead, you can write your `byte.buffer`  to a temp file, refer to the code below for more details.
Thanks.
```go
	// first create a temp file
	filePath := ("./my-file.tmp")
	file, err := os.OpenFile(filePath, os.O_CREATE|os.O_TRUNC|os.O_RDWR, 666)
	if err != nil {
		panic("error creating temp file")
	}
	defer file.Close()
	// write the buffer content to the temp file
	_, err = file.Write(buf.Bytes())
	if err != nil {
		panic("error writing to the temp file")
	}
	// add the file to the attachments
	mailer.SetAttachments([]mailing.Attachment{
		{
			Name: "your attachment file name",
			Path: filePath,
		},
	})

	// make sure to remove the temp file after done sending
	os.Remove(filePath)
```
